export default defineEventHandler(() => {
	return [
		{
			id: 1,
			name: 'Eustace Kaminski',
			email: 'fkildea4r@ucsd.edu',
			address: 'Mount Vernon, New York, United States',
		},
		{
			id: 2,
			name: 'Brewer Gwillim',
			email: 'qkopman2y@princeton.edu',
			address: 'Coppell, Texas, United States',
		},
		{
			id: 3,
			name: 'Domini Aitken',
			email: 'hmanketell1n@cbslocal.com',
			address: 'Fresno, California, United States',
		},
		{
			id: 4,
			name: 'Dave Olfert',
			email: 'aovens6f@unesco.org',
			address: 'Escondido, California, United States',
		},
		{
			id: 5,
			name: 'Brewer Rogeon',
			email: 'fegdalej@infoseek.co.jp',
			address: 'Denton, Texas, United States',
		},
		{
			id: 6,
			name: 'Krishna Spellissy',
			email: 'idrains4u@google.com.hk',
			address: 'New Braunfels, Texas, United States',
		},
		{
			id: 7,
			name: 'Filippa Cunliffe',
			email: 'prawlingson4w@phoca.cz',
			address: 'Lubbock, Texas, United States',
		},
		{
			id: 8,
			name: 'Imogene Albin',
			email: 'yslides4g@bbc.co.uk',
			address: 'Iowa City, Iowa, United States',
		},
		{
			id: 9,
			name: 'Harmony Eagell',
			email: 'rdossettp@cpanel.net',
			address: 'Greenville, North Carolina, United States',
		},
		{
			id: 10,
			name: 'Catharina Brito',
			email: 'jgimson2@un.org',
			address: 'Sheboygan, Wisconsin, United States',
		},
		{
			id: 11,
			name: 'Tamiko Reasce',
			email: 'nrogeon5o@studiopress.com',
			address: 'Cranston, Rhode Island, United States',
		},
		{
			id: 12,
			name: 'Claretta Morling',
			email: 'kturton37@github.com',
			address: 'Huntsville, Texas, United States',
		},
		{
			id: 13,
			name: 'Rhianon Borth',
			email: 'rhalsted24@photobucket.com',
			address: 'Mission, Texas, United States',
		},
		{
			id: 14,
			name: 'Annadiana Olfert',
			email: 'efeldheim44@utexas.edu',
			address: 'Hemet, California, United States',
		},
		{
			id: 15,
			name: 'Shelton Morling',
			email: 'cbrabham3p@a8.net',
			address: 'Duluth, Minnesota, United States',
		},
		{
			id: 16,
			name: 'Neron Hattersley',
			email: 'iiorizzo2l@geocities.jp',
			address: 'Dothan, Alabama, United States',
		},
		{
			id: 17,
			name: 'Lyon Fifield',
			email: 'ssambiedgen@europa.eu',
			address: 'Rancho Palos Verdes, California, United States',
		},
		{
			id: 18,
			name: 'Marinna Dobbison',
			email: 'kaitkeny@telegraph.co.uk',
			address: 'Gardena, California, United States',
		},
		{
			id: 19,
			name: 'Ashil Rogeon',
			email: 'vhefforde46@fc2.com',
			address: 'La Mesa, California, United States',
		},
		{
			id: 20,
			name: 'Gilemette Boyle',
			email: 'lkenafaque2o@utexas.edu',
			address: 'Watsonville, California, United States',
		},
		{
			id: 21,
			name: 'Halie Benjefield',
			email: 'mharken63@nymag.com',
			address: 'Glendale, Arizona, United States',
		},
		{
			id: 22,
			name: 'Ulick Vanin',
			email: 'gfraschetti54@independent.co.uk',
			address: 'Taunton, Massachusetts, United States',
		},
		{
			id: 23,
			name: 'Elvera Matissoff',
			email: 'mharken63@nymag.com',
			address: 'Milwaukee, Wisconsin, United States',
		},
		{
			id: 24,
			name: 'Haley Venneur',
			email: 'lstovine51@irs.gov',
			address: 'Buena Park, California, United States',
		},
		{
			id: 25,
			name: 'Neron Meddows',
			email: 'bcameli28@t.co',
			address: 'Bayonne, New Jersey, United States',
		},
		{
			id: 26,
			name: 'Richardo Guy',
			email: 'alenton3w@pinterest.com',
			address: 'Addison, Illinois, United States',
		},
		{
			id: 27,
			name: 'Lorelle Benjefield',
			email: 'lstovine51@irs.gov',
			address: 'Stockton, California, United States',
		},
		{
			id: 28,
			name: 'Inga Handrik',
			email: 'tolenchenko3i@chron.com',
			address: 'Oak Lawn, Illinois, United States',
		},
		{
			id: 29,
			name: 'Katie Carnoghan',
			email: 'kaitkeny@telegraph.co.uk',
			address: 'St. George, Utah, United States',
		},
		{
			id: 30,
			name: 'Caesar Bonick',
			email: 'sberryann4q@ebay.co.uk',
			address: 'Woodbury, Minnesota, United States',
		},
		{
			id: 31,
			name: 'Vachel Stachini',
			email: 'ahemerijk3a@wikimedia.org',
			address: 'Coral Springs, Florida, United States',
		},
		{
			id: 32,
			name: 'Hesther Meddows',
			email: 'alenton3w@pinterest.com',
			address: 'Long Beach, California, United States',
		},
		{
			id: 33,
			name: 'Dorolice Biggin',
			email: 'carckoll8@ebay.co.uk',
			address: 'Oro Valley, Arizona, United States',
		},
		{
			id: 34,
			name: 'Brewer Stovine',
			email: 'cfendt3j@narod.ru',
			address: 'Spokane, Washington, United States',
		},
		{
			id: 35,
			name: 'Marisa Ference',
			email: 'aspata6c@redcross.org',
			address: 'Temple, Texas, United States',
		},
		{
			id: 36,
			name: 'Mar Warbrick',
			email: 'bkersey66@scientificamerican.com',
			address: 'Portage, Michigan, United States',
		},
		{
			id: 37,
			name: 'Annora Keitley',
			email: 'amccardle5h@godaddy.com',
			address: 'Sugar Land, Texas, United States',
		},
		{
			id: 38,
			name: 'Denis Feldheim',
			email: 'msleite2m@qq.com',
			address: 'Oakley, California, United States',
		},
		{
			id: 39,
			name: 'Zaneta Hamsley',
			email: 'ekeitley3v@github.com',
			address: 'Miramar, Florida, United States',
		},
		{
			id: 40,
			name: 'Andre Werner',
			email: 'acafe13@xinhuanet.com',
			address: 'Chesterfield, Missouri, United States',
		},
		{
			id: 41,
			name: 'Quinlan Fraschetti',
			email: 'danten3q@bbc.co.uk',
			address: 'Rochester, New York, United States',
		},
		{
			id: 42,
			name: 'Jim Nind',
			email: 'nrogeon5o@studiopress.com',
			address: 'Coral Gables, Florida, United States',
		},
		{
			id: 43,
			name: 'Eustace Melley',
			email: 'hhammerson3g@imageshack.us',
			address: 'Westminster, California, United States',
		},
		{
			id: 44,
			name: 'Cristionna West-Frimley',
			email: 'svanine@flavors.me',
			address: 'Orlando, Florida, United States',
		},
		{
			id: 45,
			name: 'Armin Cornish',
			email: 'pludron5t@nymag.com',
			address: 'Lima, Ohio, United States',
		},
		{
			id: 46,
			name: 'Ricki Aitken',
			email: 'svanine@flavors.me',
			address: 'Coral Springs, Florida, United States',
		},
		{
			id: 47,
			name: 'Richardo Keitley',
			email: 'hwarbrick1s@alibaba.com',
			address: 'Ocala, Florida, United States',
		},
		{
			id: 48,
			name: 'Fawne Mitchely',
			email: 'gwerner4h@so-net.ne.jp',
			address: 'Sacramento, California, United States',
		},
		{
			id: 49,
			name: 'Hilario Eccleston',
			email: 'rcodner0@berkeley.edu',
			address: 'Macon, Georgia, United States',
		},
		{
			id: 50,
			name: 'Garik Galle',
			email: 'dleavy2i@qq.com',
			address: 'West Allis, Wisconsin, United States',
		},
	]
})
